version: 2
jobs:
  build:
    docker:
      - image: circleci/php:7.1-cli-stretch-node-browsers
    steps:
      - checkout
      - run: echo "hello world"
  deploy:
      - checkout
workflows:
  version: 2
  sample:
    - build
    - deploy
