version: 2
jobs:
  build:
    docker:
      - image: circleci/php:7.1-cli-stretch-node-browsers
    steps:
      - checkout
      - run: echo "hello world"
  deploy:
    docker:
      - image: circleci/php:7.1-cli-stretch-node-browsers
    steps:
      - checkout
      - run: echo "hello world"
workflows:
  version: 2
  sample:
    jobs:
      - build
      - deploy:
          requires:
            - build
