version: 2
jobs:
  build:
    docker:
      - image: circleci/php:7.1-cli-stretch-node-browsers
    steps:
      - checkout
      - run: echo "hello world"
  deploy:
    docker:
      - image: circleci/php:7.1-cli-stretch-node-browsers
    steps:
      - checkout
      - run: echo "hello world"
workflows:
  version: 2
  sample:
    jobs:
      - build
      - HOLD-FRONT-BUILD: # ボタン押したら実行。
          type: approval
          filters:
            branches:
              ignore: master # masterにpushさせるのは微妙なのでやらない
      - deploy:
          requires:
            - build
          filters:
            branches:
              only:
                - master
